-- ============================================================
-- BRAW — Supabase schema.
--
-- Run this once, whole, in the Supabase SQL editor. It is written to be
-- re-runnable: every object is created if-not-exists and every policy is
-- dropped before it is recreated, so applying it twice is harmless.
--
-- Three rules this file is built around:
--
--   1. The browser only ever holds the *anon* key, which is public by
--      design. Row-level security is therefore the only thing standing
--      between one user's data and another's. Every table below has RLS
--      enabled and denies by default. Nothing is left readable "because
--      the client would never ask".
--
--   2. Money is never computed in the browser. Prices live in `products`
--      and orders are created through `create_order()`, which prices the
--      basket server-side. A client that POSTs its own total is ignored.
--
--   3. Photographs are the user's, not ours. They upload only when they
--      ask to, into a private bucket partitioned by user id, and deleting
--      the account deletes the rows and the objects with it.
-- ============================================================

-- gen_random_uuid()
create extension if not exists pgcrypto;


-- ============================================================
-- profiles
--
-- One row per account. `data` is the same profile document the app
-- already keeps in the browser (trips, XP, achievements, stamps), stored
-- whole rather than normalised.
--
-- That is a deliberate trade. Normalising trips into their own tables
-- would be the better shape for reporting, but the client has no build
-- step and no ORM, and every extra table is another join to hand-write
-- in fetch(). One document round-trips exactly as the local backup does,
-- which means the sync path and the export path stay the same code.
-- When this moves to a dedicated server, split it then — `data` carries
-- everything needed to do so.
--
-- `revision` is bumped by the client on every push and is what makes
-- conflict detection possible: a device that pushes with a stale
-- revision is told, rather than quietly overwriting the other device.
-- ============================================================
create table if not exists public.profiles (
  id           uuid primary key references auth.users (id) on delete cascade,
  display_name text not null default 'Explorer',
  data         jsonb not null default '{}'::jsonb,
  revision     bigint not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

comment on column public.profiles.data is
  'Whole profile document: trips, xp, achievements, stamps, activity. Same shape as the local backup file.';
comment on column public.profiles.revision is
  'Monotonic counter. A push carrying a revision other than the stored one is rejected as a conflict.';

alter table public.profiles enable row level security;

drop policy if exists "profiles are private to their owner" on public.profiles;
drop policy if exists "read your own profile" on public.profiles;
create policy "read your own profile"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "rename yourself" on public.profiles;
create policy "rename yourself"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- Note that only `display_name` is writable here. The document itself
-- goes through push_profile() so the revision check cannot be stepped
-- around — see the privileges section at the foot of this file.


-- ============================================================
-- photos
--
-- Metadata only. The image bytes live in Storage; this table is what
-- makes them findable and is what an order references.
--
-- `id` is generated by the client and reused as the storage filename so
-- a half-finished upload can be retried without creating a duplicate.
-- It is text, not uuid, because the local store mints ids offline.
-- ============================================================
create table if not exists public.photos (
  id           text primary key,
  user_id      uuid not null references auth.users (id) on delete cascade,
  trip_id      text,
  poi_id       text not null,
  taken_at     timestamptz,
  width        int,
  height       int,
  bytes        int,
  storage_path text not null,
  created_at   timestamptz not null default now()
);

create index if not exists photos_user_trip_idx on public.photos (user_id, trip_id);

alter table public.photos enable row level security;

drop policy if exists "photos are private to their owner" on public.photos;
create policy "photos are private to their owner"
  on public.photos for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);


-- ============================================================
-- products
--
-- The price list, and the only place a price is allowed to come from.
-- Readable by everyone including signed-out visitors, so the shop can
-- be browsed before anyone makes an account. Writable through the API
-- by nobody — there is no policy granting insert, update or delete, and
-- with RLS on that means those are denied. Edit rows in the Supabase
-- dashboard, which uses the service role and bypasses RLS.
--
-- `name` and `blurb` are jsonb keyed by language: {"en": "...", "pl": "..."}
-- so the shop stays bilingual without a second table.
-- ============================================================
create table if not exists public.products (
  id          text primary key,
  kind        text not null check (kind in ('calendar', 'prints', 'magnet', 'poster', 'sticker')),
  name        jsonb not null,
  blurb       jsonb not null default '{}'::jsonb,
  price_pence int not null check (price_pence >= 0),
  currency    text not null default 'GBP',
  -- How many photographs the product consumes. A calendar takes twelve;
  -- a magnet takes one. create_order() validates the basket against this.
  photo_count int not null default 0 check (photo_count >= 0),
  active      boolean not null default true,
  meta        jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

alter table public.products enable row level security;

drop policy if exists "anyone may read the price list" on public.products;
create policy "anyone may read the price list"
  on public.products for select
  using (active);


-- ============================================================
-- orders
--
-- Created only through create_order() below. There is no insert policy,
-- so a client cannot write its own row and cannot invent a total.
--
-- Users may read their own orders, and may cancel one that has not been
-- paid yet. Everything else — marking an order paid, fulfilled, or
-- refunded — happens from the fulfilment side using the service role.
-- ============================================================
create table if not exists public.orders (
  id          uuid primary key default gen_random_uuid(),
  ref         text not null unique,
  user_id     uuid not null references auth.users (id) on delete cascade,
  product_id  text not null references public.products (id),
  kind        text not null,
  status      text not null default 'draft'
                check (status in ('draft', 'submitted', 'paid', 'fulfilled', 'cancelled')),
  -- [{ photo_id, month, caption }, ...] — validated by create_order().
  items       jsonb not null default '[]'::jsonb,
  total_pence int not null,
  currency    text not null default 'GBP',
  -- Left null by the app. Delivery details are taken by the shop that
  -- actually ships the parcel; there is no reason for this database to
  -- hold a home address as well.
  contact     jsonb,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists orders_user_idx on public.orders (user_id, created_at desc);

alter table public.orders enable row level security;

drop policy if exists "orders are readable by the person who placed them" on public.orders;
create policy "orders are readable by the person who placed them"
  on public.orders for select
  using (auth.uid() = user_id);

drop policy if exists "an unpaid order may be cancelled by its owner" on public.orders;
create policy "an unpaid order may be advanced or cancelled by its owner"
  on public.orders for update
  using (auth.uid() = user_id and status in ('draft', 'submitted'))
  with check (auth.uid() = user_id and status in ('submitted', 'cancelled'));

-- A policy decides *which rows* may be updated, never which columns, so
-- on its own the one above would happily let someone set their own
-- total_pence to zero while "cancelling". Column privileges are the tool
-- for that, and they are granted at the foot of this file.


-- ============================================================
-- Keep updated_at honest
-- ============================================================
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch on public.profiles;
create trigger profiles_touch before update on public.profiles
  for each row execute function public.touch_updated_at();

drop trigger if exists orders_touch on public.orders;
create trigger orders_touch before update on public.orders
  for each row execute function public.touch_updated_at();


-- ============================================================
-- A profile row appears with the account
--
-- Without this the client would have to insert its own profile after
-- signup, which fails while the email is still unconfirmed. Doing it in
-- a trigger means the row exists from the first moment the account does.
-- ============================================================
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''), 'Explorer')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();


-- ============================================================
-- push_profile(data, revision)
--
-- Optimistic concurrency. The client sends the revision it last saw; if
-- the stored revision has moved on, another device has written since and
-- the push is refused rather than applied. The client then has a real
-- choice to offer the user instead of silently destroying whichever
-- history happened to arrive second.
--
-- Returns the stored revision either way, so a refusal is still useful.
--
-- security definer because `authenticated` deliberately has no update
-- privilege on profiles; routing every write through here is what makes
-- the revision check binding. It still only ever touches the caller's
-- own row — auth.uid() is the sole thing it will write to, and it is
-- not a parameter, so there is nothing for a caller to point elsewhere.
-- ============================================================
create or replace function public.push_profile(p_data jsonb, p_revision bigint)
returns table (ok boolean, revision bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_rev bigint;
begin
  select p.revision into current_rev from public.profiles p where p.id = auth.uid();

  if current_rev is null then
    return query select false, -1::bigint;   -- no such profile, or not signed in
    return;
  end if;

  if current_rev <> p_revision then
    return query select false, current_rev;  -- somebody else got there first
    return;
  end if;

  update public.profiles
     set data = p_data, revision = current_rev + 1
   where id = auth.uid();

  return query select true, current_rev + 1;
end;
$$;



-- ============================================================
-- create_order(product, items)
--
-- The only way an order comes into existence. Prices are read from
-- `products`, never accepted from the caller, and the basket is checked
-- against the product's photo_count and against the caller actually
-- owning every photograph referenced.
--
-- security definer, because it writes to a table the caller has no
-- insert policy on. search_path is pinned, which matters for a definer
-- function: without it a caller could shadow `products` with their own
-- table and buy a calendar for nothing.
-- ============================================================
create or replace function public.create_order(p_product_id text, p_items jsonb)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  prod    public.products%rowtype;
  n_items int;
  n_refs  int;
  n_owned int;
  new_ref text;
  result  public.orders%rowtype;
begin
  if auth.uid() is null then
    raise exception 'not signed in' using errcode = '42501';
  end if;

  select * into prod from public.products where id = p_product_id and active;
  if not found then
    raise exception 'no such product: %', p_product_id using errcode = '22023';
  end if;

  if jsonb_typeof(p_items) <> 'array' then
    raise exception 'items must be an array' using errcode = '22023';
  end if;

  n_items := jsonb_array_length(p_items);
  if n_items <> prod.photo_count then
    raise exception 'this product takes % photographs, got %', prod.photo_count, n_items
      using errcode = '22023';
  end if;

  -- Every referenced photograph must exist and belong to the caller.
  -- Compared on distinct ids, because the same photograph appearing in
  -- two months is a legitimate basket and must not read as a missing
  -- one. Counting owned rows rather than trusting the ids also rejects
  -- an order referencing a photo deleted between building and buying.
  select count(distinct e ->> 'photo_id') into n_refs
    from jsonb_array_elements(p_items) e;

  select count(*) into n_owned
    from public.photos ph
   where ph.user_id = auth.uid()
     and ph.id in (select distinct e ->> 'photo_id' from jsonb_array_elements(p_items) e);

  if n_owned <> n_refs then
    raise exception 'order references % photographs you do not have', n_refs - n_owned
      using errcode = '42501';
  end if;

  -- Short and quotable down a phone line. The alphabet leaves out every
  -- pair that gets misheard or mistyped — no 0/O, 1/I/L, 5/S, 2/Z — and
  -- has no vowels, so a reference can never come out as a real word.
  new_ref := 'BRAW-' || translate(
    substring(encode(gen_random_bytes(8), 'hex') from 1 for 6),
    '0123456789abcdef',
    '346789CDFHJKMNPR'
  );

  insert into public.orders (ref, user_id, product_id, kind, items, total_pence, currency)
  values (new_ref, auth.uid(), prod.id, prod.kind, p_items, prod.price_pence, prod.currency)
  returning * into result;

  return result;
end;
$$;



-- ============================================================
-- Storage: the photo bucket
--
-- Private. Reading an object requires a signed URL, which the owner can
-- mint and nobody else can. Paths are "<user id>/<photo id>.jpg" and
-- every policy below pins the first path segment to the caller, so one
-- account cannot write into another's folder.
-- ============================================================
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('journey-photos', 'journey-photos', false, 12582912, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update
  set public             = excluded.public,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "read your own photographs" on storage.objects;
create policy "read your own photographs"
  on storage.objects for select
  using (bucket_id = 'journey-photos' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "upload into your own folder" on storage.objects;
create policy "upload into your own folder"
  on storage.objects for insert
  with check (bucket_id = 'journey-photos' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "replace your own photographs" on storage.objects;
create policy "replace your own photographs"
  on storage.objects for update
  using (bucket_id = 'journey-photos' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "delete your own photographs" on storage.objects;
create policy "delete your own photographs"
  on storage.objects for delete
  using (bucket_id = 'journey-photos' and (storage.foldername(name))[1] = auth.uid()::text);


-- ============================================================
-- Privileges
--
-- Stated in full rather than inherited, for two reasons. Supabase hands
-- `anon` and `authenticated` broad table privileges by default, so the
-- careful column rules above would be undone by defaults set elsewhere
-- unless they are taken back here. And when this moves to a server that
-- is not Supabase, these lines are the whole access model, written down
-- in one place instead of assumed.
--
-- Row-level security still decides which *rows*. These decide which
-- tables and columns are reachable at all; the two work together, and
-- neither is sufficient alone.
-- ============================================================
grant usage on schema public to anon, authenticated;

revoke all on public.profiles, public.photos, public.orders, public.products
  from anon, authenticated;

-- The shop window is open to everyone, signed in or not.
grant select on public.products to anon, authenticated;

-- Your own profile: readable, renameable, and otherwise only through
-- push_profile(). The row itself is created by the signup trigger.
grant select on public.profiles to authenticated;
grant update (display_name) on public.profiles to authenticated;

-- Photograph metadata is ordinary CRUD; RLS pins it to the owner.
grant select, insert, update, delete on public.photos to authenticated;

-- Orders are created by create_order() and afterwards the only column a
-- client may touch is status, to submit or cancel.
grant select on public.orders to authenticated;
grant update (status) on public.orders to authenticated;

revoke all on function public.create_order(text, jsonb)  from public, anon;
revoke all on function public.push_profile(jsonb, bigint) from public, anon;
grant execute on function public.create_order(text, jsonb)  to authenticated;
grant execute on function public.push_profile(jsonb, bigint) to authenticated;


-- ============================================================
-- Seed the price list
--
-- Placeholder prices. Set real ones before taking money — and note that
-- these are the numbers the server will charge, so editing them here is
-- the whole job; nothing in the client needs redeploying.
-- ============================================================
insert into public.products (id, kind, name, blurb, price_pence, photo_count, meta) values
  ('calendar-a4',  'calendar', '{"en":"A4 wall calendar","pl":"Kalendarz ścienny A4"}',
                               '{"en":"Twelve months, twelve of your photographs.","pl":"Dwanaście miesięcy, dwanaście Twoich zdjęć."}',
                               2400, 12, '{"print_px_min": 1748, "size": "A4 landscape"}'),
  ('prints-six',   'prints',   '{"en":"Six 6×4 prints","pl":"Sześć odbitek 6×4"}',
                               '{"en":"Your six best stops, on proper photo paper.","pl":"Sześć najlepszych przystanków na prawdziwym papierze."}',
                               900,  6,  '{"print_px_min": 1200}'),
  ('magnet-one',   'magnet',   '{"en":"Fridge magnet","pl":"Magnes na lodówkę"}',
                               '{"en":"One photograph, 70×50mm.","pl":"Jedno zdjęcie, 70×50 mm."}',
                               450,  1,  '{"print_px_min": 600}'),
  ('poster-a3',    'poster',   '{"en":"A3 route poster","pl":"Plakat trasy A3"}',
                               '{"en":"Your route drawn as a map, with one photograph inset.","pl":"Twoja trasa jako mapa, z jednym zdjęciem."}',
                               1800, 1,  '{"print_px_min": 2480}')
on conflict (id) do nothing;
