# -*- coding: utf-8 -*-
"""New locations, written once with both languages, split into
data.js (structure) and i18n-content.js (Polish) by add_pois.py.

Fields: id, name, region, lat, lon, tags, xp, pop, icon, time,
        blurb (English), pl_name, pl_blurb
"""

NEW = [
# ============================================================ EDINBURGH
dict(id='national-museum', name='National Museum of Scotland', region='Edinburgh & Lothians',
     lat=55.9469, lon=-3.1896, tags=['city','culture','history','family','art'], xp=30, pop=9, icon='🦕', time='3 hrs',
     blurb='Dolly the sheep, a Lewis chessman and a whale skeleton under a Victorian glass roof. Free, enormous, and the roof terrace has one of the best views in town.',
     pl_name='Muzeum Narodowe Szkocji',
     pl_blurb='Owca Dolly, figura szachowa z Lewis i szkielet wieloryba pod wiktoriańskim szklanym dachem. Wstęp wolny, ogrom, a z tarasu na dachu jeden z najlepszych widoków w mieście.'),
dict(id='scottish-national-gallery', name='Scottish National Gallery', region='Edinburgh & Lothians',
     lat=55.9507, lon=-3.1959, tags=['city','art','culture'], xp=25, pop=7, icon='🖼️', time='1.5 hrs',
     blurb='Titian, Vermeer and Raeburn’s skating minister, free, right on Princes Street between the Old Town and the New.',
     pl_name='Szkocka Galeria Narodowa',
     pl_blurb='Tycjan, Vermeer i łyżwiarz Raeburna, za darmo, przy samej Princes Street między Starym a Nowym Miastem.'),
dict(id='holyrood-palace', name='Palace of Holyroodhouse', region='Edinburgh & Lothians',
     lat=55.9527, lon=-3.1722, tags=['castle','royal','history','city'], xp=35, pop=8, icon='👑', time='2 hrs',
     blurb='The King’s official residence in Scotland, at the foot of the Royal Mile. Mary, Queen of Scots lived here, and her secretary was murdered in the room they will show you.',
     pl_name='Pałac Holyroodhouse',
     pl_blurb='Oficjalna rezydencja króla w Szkocji, u stóp Royal Mile. Mieszkała tu Maria Stuart, a jej sekretarza zamordowano w pokoju, który Ci pokażą.'),
dict(id='dean-village', name='Dean Village', region='Edinburgh & Lothians',
     lat=55.9520, lon=-3.2180, tags=['city','scenic','village','history'], xp=20, pop=7, icon='🏘️', time='1 hr',
     blurb='A former milling hamlet on the Water of Leith, five minutes from Princes Street and about four hundred years away from it.',
     pl_name='Dean Village',
     pl_blurb='Dawna osada młynarska nad Water of Leith, pięć minut od Princes Street i jakieś czterysta lat od niej.'),
dict(id='water-of-leith', name='Water of Leith Walkway', region='Edinburgh & Lothians',
     lat=55.9560, lon=-3.2260, tags=['city','nature','river','hiking'], xp=20, pop=6, icon='🌳', time='2 hrs',
     blurb='Twelve miles of wooded riverside path threading the whole city, with Antony Gormley figures standing in the water along the way.',
     pl_name='Szlak nad Water of Leith',
     pl_blurb='Dwadzieścia kilometrów zalesionej ścieżki nad rzeką przez całe miasto, a po drodze figury Antony’ego Gormleya stojące w wodzie.'),
dict(id='leith-shore', name='The Shore, Leith', region='Edinburgh & Lothians',
     lat=55.9757, lon=-3.1700, tags=['city','food','coast','culture'], xp=25, pop=7, icon='🦪', time='evening',
     blurb='Edinburgh’s old port, now the best eating in the city — Michelin stars and chip shops on the same cobbled quay.',
     pl_name='The Shore, Leith',
     pl_blurb='Stary port Edynburga, dziś najlepsze jedzenie w mieście — gwiazdki Michelin i smażalnie ryb na tym samym brukowanym nabrzeżu.'),
dict(id='portobello-beach', name='Portobello Beach', region='Edinburgh & Lothians',
     lat=55.9540, lon=-3.1130, tags=['beach','coast','family','city','wildswim'], xp=20, pop=6, icon='🏖️', time='2 hrs',
     blurb='Two miles of sand with a Victorian promenade, twenty minutes from the castle by bus. Swimmers go in all year, which tells you something about them.',
     pl_name='Plaża Portobello',
     pl_blurb='Trzy kilometry piasku z wiktoriańską promenadą, dwadzieścia minut autobusem od zamku. Pływacy wchodzą tu przez cały rok, co mówi o nich swoje.'),
dict(id='greyfriars', name='Greyfriars Kirkyard', region='Edinburgh & Lothians',
     lat=55.9470, lon=-3.1913, tags=['history','mystery','city','folklore'], xp=25, pop=7, icon='🐕', time='1 hr',
     blurb='A loyal terrier, a covenanters’ prison, and surnames on the stones that a certain author borrowed for her wizards.',
     pl_name='Cmentarz Greyfriars',
     pl_blurb='Wierny terier, więzienie kowenantczyków i nazwiska na płytach, które pewna autorka pożyczyła swoim czarodziejom.'),
dict(id='royal-botanic-edinburgh', name='Royal Botanic Garden Edinburgh', region='Edinburgh & Lothians',
     lat=55.9650, lon=-3.2100, tags=['nature','family','city','forest'], xp=25, pop=7, icon='🌿', time='2 hrs',
     blurb='Seventy acres and a Victorian glasshouse, founded in 1670 as a physic garden. Free to walk, and the view of the skyline from the top lawn is the one on the postcards.',
     pl_name='Królewski Ogród Botaniczny w Edynburgu',
     pl_blurb='Dwadzieścia osiem hektarów i wiktoriańska palmiarnia, założone w 1670 roku jako ogród zielarski. Wstęp wolny, a widok na panoramę z górnego trawnika to ten z pocztówek.'),
dict(id='scott-monument', name='The Scott Monument', region='Edinburgh & Lothians',
     lat=55.9520, lon=-3.1930, tags=['city','history','views','engineering'], xp=20, pop=7, icon='🗼', time='45 min',
     blurb='287 steps up the largest monument to a writer anywhere in the world, and the staircase narrows the whole way.',
     pl_name='Pomnik Scotta',
     pl_blurb='287 stopni na największy pomnik pisarza na świecie, a schody zwężają się przez całą drogę.'),
dict(id='edinburgh-zoo', name='Edinburgh Zoo', region='Edinburgh & Lothians',
     lat=55.9420, lon=-3.2680, tags=['family','wildlife','city'], xp=25, pop=7, icon='🐧', time='3 hrs',
     blurb='Built on a hillside, so you climb as you go. The penguin parade has been running since the 1950s and is exactly as good as it sounds.',
     pl_name='Zoo w Edynburgu',
     pl_blurb='Zbudowane na zboczu, więc idziesz cały czas pod górę. Parada pingwinów odbywa się od lat 50. i jest dokładnie tak dobra, jak brzmi.'),
dict(id='grassmarket', name='The Grassmarket', region='Edinburgh & Lothians',
     lat=55.9475, lon=-3.1955, tags=['city','food','history','culture'], xp=20, pop=7, icon='🍺', time='evening',
     blurb='Pubs under the castle rock, on the square where they used to hang people. One inn is named after a woman who survived it.',
     pl_name='Grassmarket',
     pl_blurb='Puby pod skałą zamkową, na placu, gdzie kiedyś wieszano ludzi. Jedna gospoda nosi imię kobiety, która to przeżyła.'),

# ============================================================== GLASGOW
dict(id='riverside-museum', name='Riverside Museum', region='Glasgow & Clyde',
     lat=55.8656, lon=-4.3060, tags=['city','culture','family','engineering'], xp=30, pop=8, icon='🚋', time='2.5 hrs',
     blurb='Zaha Hadid’s zigzag shed full of trams, locomotives and a recreated 1900s street, with a tall ship moored outside. Free.',
     pl_name='Riverside Museum',
     pl_blurb='Zygzakowata hala Zahy Hadid pełna tramwajów, lokomotyw i odtworzonej ulicy z 1900 roku, a przy nabrzeżu cumuje żaglowiec. Wstęp wolny.'),
dict(id='glasgow-science-centre', name='Glasgow Science Centre', region='Glasgow & Clyde',
     lat=55.8590, lon=-4.2940, tags=['family','city','engineering','culture'], xp=25, pop=7, icon='🔬', time='3 hrs',
     blurb='Three floors of things to press beside the Clyde, plus a planetarium and a 127-metre tower that turns to face the wind.',
     pl_name='Centrum Nauki w Glasgow',
     pl_blurb='Trzy piętra rzeczy do naciskania nad Clyde, plus planetarium i 127-metrowa wieża, która obraca się do wiatru.'),
dict(id='glasgow-cathedral', name='Glasgow Cathedral', region='Glasgow & Clyde',
     lat=55.8628, lon=-4.2350, tags=['history','ancient','city','mystery'], xp=30, pop=7, icon='⛪', time='1.5 hrs',
     blurb='The only medieval cathedral on the Scottish mainland to survive the Reformation complete, built over the tomb of the city’s founder.',
     pl_name='Katedra w Glasgow',
     pl_blurb='Jedyna średniowieczna katedra na szkockim lądzie stałym, która przetrwała reformację w całości, wzniesiona nad grobem założyciela miasta.'),
dict(id='burrell-collection', name='The Burrell Collection, Pollok Park', region='Glasgow & Clyde',
     lat=55.8280, lon=-4.3100, tags=['art','culture','nature','city','family'], xp=30, pop=7, icon='🏺', time='3 hrs',
     blurb='One shipping magnate’s eight thousand objects — Degas, Ming, medieval glass — in a glass building in a country park with Highland cattle outside.',
     pl_name='Kolekcja Burrella, Pollok Park',
     pl_blurb='Osiem tysięcy obiektów jednego magnata żeglugowego — Degas, dynastia Ming, średniowieczne witraże — w szklanym budynku w parku, a za oknem szkockie bydło.'),
dict(id='glasgow-botanic', name='Glasgow Botanic Gardens', region='Glasgow & Clyde',
     lat=55.8790, lon=-4.2900, tags=['nature','city','family'], xp=20, pop=6, icon='🌴', time='1.5 hrs',
     blurb='The Kibble Palace, a curved iron glasshouse of 1873, full of tree ferns and marble statues. Free, and warm in February.',
     pl_name='Ogród Botaniczny w Glasgow',
     pl_blurb='Kibble Palace, wygięta żelazna palmiarnia z 1873 roku, pełna paproci drzewiastych i marmurowych posągów. Wstęp wolny i ciepło w lutym.'),
dict(id='peoples-palace', name='People’s Palace & Glasgow Green', region='Glasgow & Clyde',
     lat=55.8510, lon=-4.2380, tags=['city','history','culture','family'], xp=20, pop=6, icon='🏛️', time='1.5 hrs',
     blurb='A museum of ordinary Glasgow life on the city’s oldest park, with a winter garden glasshouse stuck on the back.',
     pl_name='People’s Palace i Glasgow Green',
     pl_blurb='Muzeum zwyczajnego życia Glasgow w najstarszym parku miasta, z doklejonym z tyłu zimowym ogrodem pod szkłem.'),
dict(id='mackintosh-willow', name='Mackintosh at the Willow', region='Glasgow & Clyde',
     lat=55.8630, lon=-4.2560, tags=['art','culture','food','city'], xp=25, pop=6, icon='🫖', time='1.5 hrs',
     blurb='Charles Rennie Mackintosh designed everything here in 1903, down to the cutlery and the waitresses’ dresses. Restored and serving tea again.',
     pl_name='Mackintosh at the Willow',
     pl_blurb='Charles Rennie Mackintosh zaprojektował tu w 1903 roku wszystko, aż po sztućce i sukienki kelnerek. Odrestaurowane i znów podaje herbatę.'),
dict(id='finnieston-clyde', name='Finnieston & the Clyde Arc', region='Glasgow & Clyde',
     lat=55.8580, lon=-4.2830, tags=['city','food','culture','engineering'], xp=20, pop=7, icon='🍽️', time='evening',
     blurb='The old shipyard district turned into Glasgow’s eating strip, under the Finnieston Crane that once lifted locomotives onto ships.',
     pl_name='Finnieston i Clyde Arc',
     pl_blurb='Dawna dzielnica stoczniowa zamieniona w gastronomiczną ulicę Glasgow, pod dźwigiem Finnieston, który kiedyś ładował lokomotywy na statki.'),
dict(id='the-barras', name='The Barras & Barrowland', region='Glasgow & Clyde',
     lat=55.8550, lon=-4.2360, tags=['city','culture','food','history'], xp=20, pop=6, icon='🎪', time='2 hrs',
     blurb='A weekend market since the 1920s, and above it the Barrowland Ballroom — a sprung dance floor that bands will tell you is the best room in Britain.',
     pl_name='The Barras i Barrowland',
     pl_blurb='Weekendowy targ od lat 20. XX wieku, a nad nim Barrowland Ballroom — sprężysty parkiet, o którym zespoły mówią, że to najlepsza sala w Wielkiej Brytanii.'),

# ============================================================= ABERDEEN
dict(id='aberdeen-beach', name='Aberdeen Beach & Esplanade', region='Aberdeenshire & Angus',
     lat=57.1520, lon=-2.0800, tags=['beach','coast','city','family','wildlife'], xp=20, pop=6, icon='🌊', time='1.5 hrs',
     blurb='Two miles of sand running straight off the end of the city, with dolphins in the bay and the North Sea doing what it does.',
     pl_name='Plaża i promenada w Aberdeen',
     pl_blurb='Trzy kilometry piasku zaczynające się tuż za miastem, delfiny w zatoce i Morze Północne robiące swoje.'),
dict(id='footdee', name='Footdee (Fittie)', region='Aberdeenshire & Angus',
     lat=57.1440, lon=-2.0700, tags=['village','coast','history','city','scenic'], xp=25, pop=5, icon='⚓', time='1 hr',
     blurb='A planned fishing village of 1809 at the harbour mouth, where the cottages face inward onto squares and every shed is decorated differently.',
     pl_name='Footdee (Fittie)',
     pl_blurb='Zaplanowana wioska rybacka z 1809 roku u wylotu portu, gdzie chaty zwrócone są do wewnątrz na dziedzińce, a każda szopa ozdobiona jest inaczej.'),
dict(id='old-aberdeen', name='Old Aberdeen & King’s College', region='Aberdeenshire & Angus',
     lat=57.1650, lon=-2.1010, tags=['history','ancient','city','culture'], xp=30, pop=6, icon='🎓', time='2 hrs',
     blurb='Cobbled streets and a crown-topped chapel tower from 1495, when the university was founded by papal bull. It feels like a different town from the granite city.',
     pl_name='Stare Aberdeen i King’s College',
     pl_blurb='Brukowane uliczki i wieża kaplicy zwieńczona koroną z 1495 roku, gdy uniwersytet założono bullą papieską. Wydaje się zupełnie innym miastem niż granitowe Aberdeen.'),
dict(id='st-machars', name='St Machar’s Cathedral', region='Aberdeenshire & Angus',
     lat=57.1690, lon=-2.1030, tags=['history','ancient','city','mystery'], xp=25, pop=5, icon='⛪', time='1 hr',
     blurb='A fortified granite cathedral with twin spires and a heraldic ceiling of 48 shields. One of William Wallace’s quarters is said to be buried in the walls.',
     pl_name='Katedra św. Machara',
     pl_blurb='Ufortyfikowana granitowa katedra z bliźniaczymi iglicami i heraldycznym stropem z 48 tarczami. Podobno w murach pochowano jedną z ćwiartek ciała Williama Wallace’a.'),
dict(id='aberdeen-maritime', name='Aberdeen Maritime Museum', region='Aberdeenshire & Angus',
     lat=57.1470, lon=-2.0940, tags=['culture','history','city','engineering','family'], xp=25, pop=6, icon='🛳️', time='1.5 hrs',
     blurb='Clippers, lighthouses and a three-storey model of an oil platform, in a merchant’s house of 1593 on the old harbour street. Free.',
     pl_name='Muzeum Morskie w Aberdeen',
     pl_blurb='Klipry, latarnie morskie i trzypiętrowy model platformy wiertniczej, w domu kupieckim z 1593 roku przy starej ulicy portowej. Wstęp wolny.'),
dict(id='duthie-park', name='Duthie Park & Winter Gardens', region='Aberdeenshire & Angus',
     lat=57.1300, lon=-2.1010, tags=['nature','family','city'], xp=20, pop=5, icon='🌺', time='1.5 hrs',
     blurb='One of Europe’s largest indoor gardens, free and heated, which in an Aberdeen February is not a small thing. Cacti, koi and a talking parrot house.',
     pl_name='Duthie Park i Ogrody Zimowe',
     pl_blurb='Jeden z największych krytych ogrodów w Europie, darmowy i ogrzewany, co w aberdeeńskim lutym nie jest drobiazgiem. Kaktusy, karpie koi i gadające papugi.'),
dict(id='marischal-college', name='Marischal College', region='Aberdeenshire & Angus',
     lat=57.1490, lon=-2.0980, tags=['city','history','engineering','views'], xp=20, pop=6, icon='🏛️', time='45 min',
     blurb='The second-largest granite building in the world, a cliff of grey spikes and pinnacles that turns silver when the sun finally comes out.',
     pl_name='Marischal College',
     pl_blurb='Drugi co do wielkości budynek granitowy na świecie — klif szarych iglic i sterczyn, który srebrzeje, gdy wreszcie wyjdzie słońce.'),
dict(id='aberdeen-art-gallery', name='Aberdeen Art Gallery', region='Aberdeenshire & Angus',
     lat=57.1490, lon=-2.1030, tags=['art','culture','city','family'], xp=25, pop=6, icon='🎨', time='1.5 hrs',
     blurb='Reopened in 2019 after a rebuild that added a rooftop gallery. Strong on the Scottish Colourists, and free.',
     pl_name='Galeria Sztuki w Aberdeen',
     pl_blurb='Otwarta ponownie w 2019 roku po przebudowie, która dodała galerię na dachu. Mocna kolekcja szkockich kolorystów, wstęp wolny.'),
dict(id='torry-battery', name='Torry Battery & Dolphin Watch', region='Aberdeenshire & Angus',
     lat=57.1420, lon=-2.0640, tags=['wildlife','coast','history','views'], xp=30, pop=6, icon='🐬', time='1.5 hrs',
     blurb='A Victorian gun battery above the harbour mouth, and one of the best places in Europe to watch bottlenose dolphins from dry land. Best on a rising tide.',
     pl_name='Bateria Torry i obserwacja delfinów',
     pl_blurb='Wiktoriańska bateria dział nad wylotem portu i jedno z najlepszych miejsc w Europie, by oglądać butlonosy z suchego lądu. Najlepiej przy przypływie.'),
dict(id='balmedie-beach', name='Balmedie Beach & Dunes', region='Aberdeenshire & Angus',
     lat=57.2600, lon=-1.9900, tags=['beach','coast','nature','family','scenic'], xp=25, pop=5, icon='🏜️', time='2 hrs',
     blurb='Fourteen miles of dune system north of the city, high enough to lose the wind in and empty enough to lose everyone else.',
     pl_name='Plaża i wydmy Balmedie',
     pl_blurb='Dwadzieścia kilometrów wydm na północ od miasta, dość wysokich, by schować się przed wiatrem, i dość pustych, by zgubić wszystkich innych.'),

# ====================================================== ABERDEENSHIRE
dict(id='stonehaven-harbour', name='Stonehaven Harbour', region='Aberdeenshire & Angus',
     lat=56.9640, lon=-2.2100, tags=['village','coast','food','scenic','family'], xp=25, pop=6, icon='🦞', time='2 hrs',
     blurb='A tidy stone harbour with the open-air Art Deco lido above it, and the chip shop that claims to have invented the deep-fried Mars bar.',
     pl_name='Port w Stonehaven',
     pl_blurb='Schludny kamienny port, nad nim odkryty basen w stylu art déco, a przy nim smażalnia, która twierdzi, że wynalazła batona Mars w głębokim tłuszczu.'),
dict(id='crathes-castle', name='Crathes Castle & Gardens', region='Aberdeenshire & Angus',
     lat=57.0640, lon=-2.4380, tags=['castle','history','nature','family','mystery'], xp=35, pop=6, icon='🌷', time='2.5 hrs',
     blurb='A 16th-century tower house with painted ceilings and eight walled garden rooms with 300-year-old yew hedges. It has a Green Lady too.',
     pl_name='Zamek i ogrody Crathes',
     pl_blurb='XVI-wieczna wieża mieszkalna z malowanymi stropami i osiem ogrodowych wnętrz otoczonych murem, z 300-letnimi żywopłotami cisowymi. Ma też Zieloną Damę.'),
dict(id='craigievar-castle', name='Craigievar Castle', region='Aberdeenshire & Angus',
     lat=57.0850, lon=-2.6600, tags=['castle','history','scenic','royal'], xp=35, pop=6, icon='🏰', time='1.5 hrs',
     blurb='A pink fairytale tower finished in 1626 and barely altered since, with turrets that are said to have suggested a certain castle to Walt Disney.',
     pl_name='Zamek Craigievar',
     pl_blurb='Różowa baśniowa wieża ukończona w 1626 roku i od tego czasu niemal nietknięta, z wieżyczkami, które podobno podsunęły Waltowi Disneyowi pewien zamek.'),
dict(id='fyvie-castle', name='Fyvie Castle', region='Aberdeenshire & Angus',
     lat=57.4400, lon=-2.3950, tags=['castle','history','mystery','folklore'], xp=35, pop=5, icon='👻', time='2 hrs',
     blurb='Five towers, five families, and more ghost stories per square metre than anywhere else in the north-east — a green lady, a secret room and a curse involving three weeping stones.',
     pl_name='Zamek Fyvie',
     pl_blurb='Pięć wież, pięć rodów i więcej opowieści o duchach na metr kwadratowy niż gdziekolwiek na północnym wschodzie — zielona dama, tajemny pokój i klątwa z trzema płaczącymi kamieniami.'),
dict(id='bennachie', name='Bennachie', region='Aberdeenshire & Angus',
     lat=57.2560, lon=-2.5220, tags=['hiking','mountain','views','forest','nature'], xp=35, pop=6, icon='⛰️', time='3 hrs',
     blurb='The hill every north-easterner grows up climbing. Only 528 metres, but it stands alone, so the top gives you the whole of Aberdeenshire at once.',
     pl_name='Bennachie',
     pl_blurb='Wzgórze, na które wchodzi każdy mieszkaniec północnego wschodu. Tylko 528 metrów, ale stoi samotnie, więc ze szczytu widać całe Aberdeenshire naraz.'),
dict(id='bullers-of-buchan', name='Bullers of Buchan', region='Aberdeenshire & Angus',
     lat=57.4290, lon=-1.8180, tags=['coast','nature','wildlife','scenic','views'], xp=30, pop=5, icon='🪶', time='1.5 hrs',
     blurb='A collapsed sea cave forming a circular chasm the sea pours into, ringed by nesting puffins and kittiwakes in early summer. The path runs right along the edge.',
     pl_name='Bullers of Buchan',
     pl_blurb='Zapadnięta jaskinia morska tworząca okrągłą przepaść, do której wlewa się morze, obsadzona wczesnym latem maskonurami i mewami trójpalczastymi. Ścieżka biegnie samą krawędzią.'),
dict(id='slains-castle', name='New Slains Castle', region='Aberdeenshire & Angus',
     lat=57.4130, lon=-1.8360, tags=['castle','coast','mystery','history','scenic'], xp=35, pop=5, icon='🦇', time='1.5 hrs',
     blurb='A roofless clifftop ruin where Bram Stoker holidayed while writing, and which is generally held to have furnished Dracula with his castle. Unfenced and genuinely dangerous in wind.',
     pl_name='Nowy Zamek Slains',
     pl_blurb='Bezdachowa ruina na klifie, gdzie Bram Stoker spędzał wakacje podczas pisania i która, jak się uważa, dała Drakuli jego zamek. Bez ogrodzenia i naprawdę niebezpieczna przy wietrze.'),
dict(id='dunnottar-woods', name='Aden Country Park', region='Aberdeenshire & Angus',
     lat=57.5670, lon=-2.0740, tags=['forest','nature','family','history'], xp=20, pop=4, icon='🌲', time='2 hrs',
     blurb='230 acres of estate woodland and lake with a farming museum in the old semicircular steading. Good for a wet afternoon with children.',
     pl_name='Aden Country Park',
     pl_blurb='93 hektary lasu i jeziora dawnego majątku, z muzeum rolnictwa w starym półkolistym zabudowaniu gospodarczym. Dobre na mokre popołudnie z dziećmi.'),

# ============================================================ INVERNESS
dict(id='inverness-castle', name='Inverness Castle Viewpoint', region='Loch Ness & Inverness',
     lat=57.4770, lon=-4.2250, tags=['castle','city','views','history'], xp=20, pop=6, icon='🏰', time='45 min',
     blurb='Red sandstone above the River Ness, and the terrace gives you the whole town, the river and the hills beyond it in one turn of the head.',
     pl_name='Punkt widokowy przy zamku w Inverness',
     pl_blurb='Czerwony piaskowiec nad rzeką Ness, a z tarasu jednym obrotem głowy ogarniasz całe miasto, rzekę i góry za nią.'),
dict(id='ness-islands', name='Ness Islands', region='Loch Ness & Inverness',
     lat=57.4680, lon=-4.2340, tags=['nature','city','river','family','forest'], xp=20, pop=5, icon='🌉', time='1 hr',
     blurb='Wooded river islands joined by Victorian suspension footbridges, ten minutes’ walk from the middle of Inverness and completely quiet.',
     pl_name='Wyspy Ness',
     pl_blurb='Zalesione wyspy rzeczne połączone wiktoriańskimi kładkami wiszącymi, dziesięć minut od centrum Inverness i zupełnie ciche.'),
dict(id='fort-george', name='Fort George', region='Loch Ness & Inverness',
     lat=57.5830, lon=-4.0700, tags=['history','engineering','coast','wildlife'], xp=35, pop=6, icon='🛡️', time='2.5 hrs',
     blurb='The mightiest artillery fortification in Britain, built after Culloden to make sure it never happened again, and never attacked. Dolphins pass the ramparts.',
     pl_name='Fort George',
     pl_blurb='Najpotężniejsza fortyfikacja artyleryjska w Wielkiej Brytanii, zbudowana po Culloden, by to się nie powtórzyło — i nigdy nie zaatakowana. Pod wałami przepływają delfiny.'),
dict(id='cawdor-castle', name='Cawdor Castle', region='Loch Ness & Inverness',
     lat=57.5240, lon=-3.9290, tags=['castle','history','nature','mystery','film'], xp=35, pop=6, icon='🌳', time='2.5 hrs',
     blurb='Still lived in, still has a holly tree growing in the vaulted basement that the family built the tower around in 1454. Shakespeare gave the title to Macbeth; the castle came later.',
     pl_name='Zamek Cawdor',
     pl_blurb='Wciąż zamieszkany i wciąż ma ostrokrzew rosnący w sklepionej piwnicy, wokół którego rodzina zbudowała wieżę w 1454 roku. Szekspir dał ten tytuł Makbetowi; zamek powstał później.'),
dict(id='chanonry-point', name='Chanonry Point', region='Loch Ness & Inverness',
     lat=57.5750, lon=-4.0950, tags=['wildlife','coast','lighthouse','scenic','views'], xp=40, pop=7, icon='🐬', time='2 hrs',
     blurb='The single best place in Britain to see bottlenose dolphins from the shore — they hunt salmon in the narrows on a rising tide, sometimes a few metres out.',
     pl_name='Chanonry Point',
     pl_blurb='Najlepsze miejsce w Wielkiej Brytanii, by zobaczyć butlonosy z brzegu — polują na łososie w cieśninie przy przypływie, czasem kilka metrów od Ciebie.'),
dict(id='beauly-priory', name='Beauly Priory', region='Loch Ness & Inverness',
     lat=57.4780, lon=-4.4700, tags=['history','ancient','village','mystery'], xp=20, pop=4, icon='🕍', time='1 hr',
     blurb='A roofless 13th-century priory in a village square, with an elm outside that is among the oldest in Europe. Mary, Queen of Scots is supposed to have named the place.',
     pl_name='Przeorat Beauly',
     pl_blurb='Bezdachowy XIII-wieczny przeorat przy wiejskim rynku, a przed nim wiąz należący do najstarszych w Europie. Nazwę miejscu miała nadać Maria Stuart.'),
dict(id='culbin-forest', name='Culbin Forest & Sands', region='Speyside & Moray',
     lat=57.6200, lon=-3.6800, tags=['forest','beach','nature','cycling','wildlife'], xp=25, pop=4, icon='🌲', time='2.5 hrs',
     blurb='A forest planted onto a desert — the sand dunes that buried an entire estate in a storm in 1694 were stabilised with pines. Miles of flat trails and an empty shore.',
     pl_name='Las i piaski Culbin',
     pl_blurb='Las posadzony na pustyni — wydmy, które w sztormie 1694 roku zasypały cały majątek, ustabilizowano sosnami. Kilometry płaskich ścieżek i pusty brzeg.'),

# ============================================================== DUNDEE
dict(id='rrs-discovery', name='RRS Discovery', region='Fife & Dundee',
     lat=56.4570, lon=-2.9690, tags=['history','engineering','family','city','coast'], xp=30, pop=7, icon='⛵', time='2 hrs',
     blurb='Scott’s Antarctic ship, built in Dundee in 1901 and back where she started. You can go below into the cabins and the wardroom.',
     pl_name='RRS Discovery',
     pl_blurb='Antarktyczny statek Scotta, zbudowany w Dundee w 1901 roku i wrócił tam, gdzie powstał. Można zejść pod pokład do kabin i mesy.'),
dict(id='dundee-law', name='Dundee Law', region='Fife & Dundee',
     lat=56.4680, lon=-2.9840, tags=['views','city','hiking','history'], xp=20, pop=6, icon='🌄', time='1 hr',
     blurb='An extinct volcano in the middle of the city. From the top you get both Tay bridges, the Fife coast and, on a clear day, the Cairngorms.',
     pl_name='Dundee Law',
     pl_blurb='Wygasły wulkan w środku miasta. Ze szczytu widać oba mosty na Tay, wybrzeże Fife, a w pogodny dzień Cairngorms.'),
dict(id='broughty-ferry', name='Broughty Ferry & Castle', region='Fife & Dundee',
     lat=56.4670, lon=-2.8690, tags=['castle','beach','coast','village','food'], xp=25, pop=6, icon='🏖️', time='2 hrs',
     blurb='A 15th-century tower standing in the water at the river mouth, a sandy beach beside it, and the best ice cream in Tayside up the road.',
     pl_name='Broughty Ferry i zamek',
     pl_blurb='XV-wieczna wieża stojąca w wodzie u ujścia rzeki, obok piaszczysta plaża, a kawałek dalej najlepsze lody w Tayside.'),
dict(id='verdant-works', name='Verdant Works', region='Fife & Dundee',
     lat=56.4620, lon=-2.9820, tags=['history','culture','city','engineering'], xp=25, pop=5, icon='🧵', time='2 hrs',
     blurb='A restored jute mill telling the story of the trade that built Dundee — and of the women who worked it, who outnumbered the men three to one.',
     pl_name='Verdant Works',
     pl_blurb='Odrestaurowana przędzalnia juty opowiadająca o handlu, który zbudował Dundee — i o kobietach, które w nim pracowały i przewyższały mężczyzn liczbą trzy do jednego.'),
dict(id='camperdown-park', name='Camperdown Country Park', region='Fife & Dundee',
     lat=56.4880, lon=-3.0400, tags=['family','wildlife','nature','forest','city'], xp=20, pop=5, icon='🐻', time='2.5 hrs',
     blurb='400 acres of parkland with a small wildlife centre — brown bears, lynx and Scottish wildcats — and one of the largest tree collections in Scotland.',
     pl_name='Camperdown Country Park',
     pl_blurb='160 hektarów parku z małym centrum dzikiej przyrody — niedźwiedzie brunatne, rysie i żbiki szkockie — oraz jedna z największych kolekcji drzew w Szkocji.'),

# ================================================ STIRLING & PERTHSHIRE
dict(id='bannockburn', name='Bannockburn', region='Stirling & Forth Valley',
     lat=56.0930, lon=-3.9200, tags=['history','film','family'], xp=30, pop=6, icon='⚔️', time='1.5 hrs',
     blurb='Where Bruce beat a far larger English army over two days in June 1314. The visitor centre puts you inside the battle in 3D; the field itself is quiet grass.',
     pl_name='Bannockburn',
     pl_blurb='Tu Bruce pokonał znacznie liczniejszą armię angielską w ciągu dwóch dni w czerwcu 1314 roku. Centrum dla zwiedzających wprowadza Cię w bitwę w 3D; samo pole to cicha trawa.'),
dict(id='doune-castle', name='Doune Castle', region='Stirling & Forth Valley',
     lat=56.1870, lon=-4.0510, tags=['castle','history','film','mystery'], xp=35, pop=7, icon='🥥', time='1.5 hrs',
     blurb='A remarkably complete 14th-century courtyard castle, and the most filmed in Scotland — Monty Python, Outlander and Winterfell all at once. The audio guide is by Terry Jones.',
     pl_name='Zamek Doune',
     pl_blurb='Wyjątkowo dobrze zachowany XIV-wieczny zamek z dziedzińcem i najczęściej filmowany w Szkocji — Monty Python, Outlander i Winterfell naraz. Audioprzewodnik czyta Terry Jones.'),
dict(id='dunblane-cathedral', name='Dunblane Cathedral', region='Stirling & Forth Valley',
     lat=56.1900, lon=-3.9670, tags=['history','ancient','village','culture'], xp=20, pop=4, icon='⛪', time='1 hr',
     blurb='A 13th-century cathedral with a Norman tower, restored in the 1890s, in a small cathedral town of tearooms and a good bookshop.',
     pl_name='Katedra w Dunblane',
     pl_blurb='XIII-wieczna katedra z normańską wieżą, odrestaurowana w latach 90. XIX wieku, w małym miasteczku katedralnym pełnym herbaciarni i z dobrą księgarnią.'),
dict(id='scone-palace', name='Scone Palace', region='Perthshire',
     lat=56.4160, lon=-3.4370, tags=['castle','royal','history','ancient','nature'], xp=35, pop=6, icon='👑', time='2.5 hrs',
     blurb='The crowning place of Scottish kings for centuries, on the Moot Hill where the Stone of Destiny sat. Peacocks on the lawn and a hedge maze.',
     pl_name='Pałac Scone',
     pl_blurb='Miejsce koronacji szkockich królów przez stulecia, na Moot Hill, gdzie stał Kamień Przeznaczenia. Pawie na trawniku i labirynt z żywopłotu.'),
dict(id='kinnoull-hill', name='Kinnoull Hill', region='Perthshire',
     lat=56.3930, lon=-3.4000, tags=['views','hiking','forest','scenic','nature'], xp=25, pop=5, icon='🗼', time='1.5 hrs',
     blurb='A folly tower on a cliff edge above the Tay, built to look like the Rhine. Half an hour up from Perth and the view runs the whole valley.',
     pl_name='Wzgórze Kinnoull',
     pl_blurb='Wieża-kaprys na krawędzi klifu nad rzeką Tay, zbudowana tak, by przypominała Ren. Pół godziny podejścia z Perth, a widok obejmuje całą dolinę.'),
dict(id='blair-castle', name='Blair Castle', region='Perthshire',
     lat=56.7660, lon=-3.8480, tags=['castle','history','royal','family','nature'], xp=35, pop=6, icon='🏰', time='2.5 hrs',
     blurb='White-harled seat of the Atholl dukes, whose owner keeps the only legal private army in Europe. Thirty rooms, red deer in the park and a walled garden.',
     pl_name='Zamek Blair',
     pl_blurb='Bielona siedziba książąt Atholl, których właściciel utrzymuje jedyną legalną prywatną armię w Europie. Trzydzieści pokoi, jelenie w parku i ogród otoczony murem.'),
dict(id='killiecrankie', name='Pass of Killiecrankie', region='Perthshire',
     lat=56.7370, lon=-3.7780, tags=['history','forest','nature','scenic','river'], xp=25, pop=5, icon='🍁', time='1.5 hrs',
     blurb='A wooded gorge where a Jacobite charge broke a government army in 1689, and where a fleeing soldier is said to have jumped eighteen feet across the river.',
     pl_name='Przełęcz Killiecrankie',
     pl_blurb='Zalesiony wąwóz, gdzie szarża jakobitów rozbiła armię rządową w 1689 roku i gdzie uciekający żołnierz miał przeskoczyć rzekę na odległość pięciu i pół metra.'),
dict(id='loch-leven-castle', name='Loch Leven Castle', region='Perthshire',
     lat=56.2000, lon=-3.3900, tags=['castle','loch','history','mystery','wildlife'], xp=30, pop=5, icon='🚣', time='2 hrs',
     blurb='An island prison reached by small boat, where Mary, Queen of Scots was held in 1567, forced to abdicate, and from which she escaped with the help of a boy and a stolen key.',
     pl_name='Zamek Loch Leven',
     pl_blurb='Wyspiarskie więzienie, do którego dopływa się łódką; w 1567 roku trzymano tu Marię Stuart, zmuszono do abdykacji, a ona uciekła z pomocą chłopca i skradzionego klucza.'),

# ================================================================= FIFE
dict(id='falkland-palace', name='Falkland Palace', region='Fife & Dundee',
     lat=56.2530, lon=-3.2060, tags=['castle','royal','history','village','sport'], xp=30, pop=5, icon='🎾', time='2 hrs',
     blurb='A Renaissance hunting palace of the Stuarts in a conservation village, with the oldest real tennis court still in use anywhere in the world, built in 1541.',
     pl_name='Pałac Falkland',
     pl_blurb='Renesansowy pałac myśliwski Stuartów w zabytkowej wsi, z najstarszym wciąż używanym kortem do jeu de paume na świecie, zbudowanym w 1541 roku.'),
dict(id='culross', name='Culross', region='Fife & Dundee',
     lat=56.0560, lon=-3.6300, tags=['village','history','film','scenic','coast'], xp=30, pop=6, icon='🏘️', time='2 hrs',
     blurb='A complete 17th-century burgh in ochre and crow-stepped gables, so intact that Outlander used it as a village without changing much.',
     pl_name='Culross',
     pl_blurb='Kompletne XVII-wieczne miasteczko w ochrze i schodkowych szczytach, tak nienaruszone, że Outlander użył go jako wioski, niewiele zmieniając.'),
dict(id='dunfermline-abbey', name='Dunfermline Abbey & Palace', region='Fife & Dundee',
     lat=56.0710, lon=-3.4630, tags=['history','ancient','royal','city'], xp=30, pop=5, icon='🕍', time='1.5 hrs',
     blurb='Robert the Bruce is buried under the pulpit — without his heart, which went to Melrose. Scotland’s royal burial place before Iona and after Dunkeld.',
     pl_name='Opactwo i pałac w Dunfermline',
     pl_blurb='Pod amboną pochowano Roberta Bruce’a — bez serca, które trafiło do Melrose. Królewska nekropolia Szkocji po Dunkeld, a przed Ioną.'),
dict(id='aberdour-castle', name='Aberdour Castle & Silver Sands', region='Fife & Dundee',
     lat=56.0550, lon=-3.3000, tags=['castle','beach','history','family','coast'], xp=25, pop=5, icon='🏖️', time='2 hrs',
     blurb='One of the oldest standing castles in Scotland with a terraced garden and a beehive doocot, and a good sandy beach five minutes down the hill.',
     pl_name='Zamek Aberdour i Silver Sands',
     pl_blurb='Jeden z najstarszych zachowanych zamków w Szkocji, z tarasowym ogrodem i ulowym gołębnikiem, a pięć minut w dół zbocza dobra piaszczysta plaża.'),

# ============================================================ THE SOUTH
dict(id='abbotsford', name='Abbotsford, Home of Walter Scott', region='Scottish Borders',
     lat=55.5990, lon=-2.7830, tags=['history','culture','art','river','nature'], xp=30, pop=5, icon='📚', time='2 hrs',
     blurb='The house Walter Scott built with the money from his novels, stuffed with armour, Rob Roy’s gun and 9,000 books, above a bend in the Tweed.',
     pl_name='Abbotsford, dom Waltera Scotta',
     pl_blurb='Dom, który Walter Scott zbudował za pieniądze z powieści, wypchany zbrojami, strzelbą Roba Roya i 9000 książek, nad zakolem rzeki Tweed.'),
dict(id='jedburgh-abbey', name='Jedburgh Abbey', region='Scottish Borders',
     lat=55.4780, lon=-2.5540, tags=['history','ancient','mystery'], xp=25, pop=5, icon='🕍', time='1.5 hrs',
     blurb='The most complete of the four Border abbeys, its rose window still standing, burned repeatedly over three centuries for the crime of being near England.',
     pl_name='Opactwo Jedburgh',
     pl_blurb='Najlepiej zachowane z czterech opactw pogranicza, z wciąż stojącą rozetą, palone wielokrotnie przez trzy stulecia za to, że leżało blisko Anglii.'),
dict(id='scotts-view', name='Scott’s View & Dryburgh', region='Scottish Borders',
     lat=55.6000, lon=-2.6600, tags=['views','scenic','history','ancient','river'], xp=25, pop=5, icon='🔭', time='1.5 hrs',
     blurb='Walter Scott’s favourite view over the Eildon Hills, and the horses pulling his hearse are said to have stopped here out of habit. His grave is in the abbey below.',
     pl_name='Scott’s View i Dryburgh',
     pl_blurb='Ulubiony widok Waltera Scotta na wzgórza Eildon; konie ciągnące jego karawan miały się tu zatrzymać z przyzwyczajenia. Jego grób jest w opactwie poniżej.'),
dict(id='traquair-house', name='Traquair House', region='Scottish Borders',
     lat=55.6220, lon=-3.0480, tags=['castle','history','mystery','food','royal'], xp=30, pop=5, icon='🍺', time='2 hrs',
     blurb='The oldest continuously inhabited house in Scotland, over 900 years. Its main gates were closed in 1745 and will not reopen until a Stuart is on the throne. It brews its own ale.',
     pl_name='Traquair House',
     pl_blurb='Najdłużej nieprzerwanie zamieszkany dom w Szkocji, ponad 900 lat. Główną bramę zamknięto w 1745 roku i nie otworzy się, póki na tronie nie zasiądzie Stuart. Warzy własne piwo.'),
dict(id='threave-castle', name='Threave Castle', region='Dumfries & Galloway',
     lat=54.9370, lon=-3.9350, tags=['castle','history','river','wildlife','mystery'], xp=30, pop=5, icon='🚣', time='2 hrs',
     blurb='A grim island tower of the Black Douglases, reached by ringing a bell for the boatman. Ospreys nest nearby in summer.',
     pl_name='Zamek Threave',
     pl_blurb='Ponura wyspiarska wieża Czarnych Douglasów, do której dostajesz się, dzwoniąc po przewoźnika. Latem gnieżdżą się w pobliżu rybołowy.'),
dict(id='sweetheart-abbey', name='Sweetheart Abbey', region='Dumfries & Galloway',
     lat=54.9820, lon=-3.6220, tags=['history','ancient','village','mystery'], xp=25, pop=4, icon='❤️', time='1 hr',
     blurb='Red sandstone ruins founded in 1273 by Lady Devorgilla, who carried her husband’s embalmed heart with her for twenty-two years and was buried holding it.',
     pl_name='Opactwo Sweetheart',
     pl_blurb='Ruiny z czerwonego piaskowca założone w 1273 roku przez lady Devorgillę, która przez dwadzieścia dwa lata nosiła ze sobą zabalsamowane serce męża i została pochowana, trzymając je.'),
dict(id='burns-cottage', name='Burns Cottage, Alloway', region='Ayrshire & Arran',
     lat=55.4340, lon=-4.6420, tags=['history','culture','village','folklore'], xp=25, pop=6, icon='🖋️', time='2 hrs',
     blurb='The thatched two-room cottage Robert Burns was born in, in 1759, and the kirkyard down the lane where he set Tam o’ Shanter’s witches dancing.',
     pl_name='Chata Burnsa w Alloway',
     pl_blurb='Kryta strzechą dwuizbowa chata, w której w 1759 roku urodził się Robert Burns, a kawałek dalej cmentarz, gdzie kazał tańczyć wiedźmom z Tam o’ Shantera.'),
dict(id='brodick-castle', name='Brodick Castle, Arran', region='Ayrshire & Arran',
     lat=55.5980, lon=-5.1470, tags=['castle','island','nature','history','family'], xp=35, pop=6, icon='🏰', time='2.5 hrs',
     blurb='Red sandstone above Brodick Bay with a woodland garden of rhododendrons that flower in a Gulf Stream microclimate, and red squirrels in the grounds.',
     pl_name='Zamek Brodick, Arran',
     pl_blurb='Czerwony piaskowiec nad zatoką Brodick, z leśnym ogrodem rododendronów kwitnących w mikroklimacie Prądu Zatokowego i wiewiórkami rudymi na terenie posiadłości.'),

# ================================================== HIGHLANDS & ISLANDS
dict(id='plockton', name='Plockton', region='Highlands',
     lat=57.3350, lon=-5.6560, tags=['village','coast','scenic','food','film'], xp=30, pop=6, icon='🌴', time='2 hrs',
     blurb='A sheltered bay so mild that palm trees grow on the seafront, with a row of white cottages and boats on moorings. Improbable, and entirely real.',
     pl_name='Plockton',
     pl_blurb='Zatoka tak osłonięta i łagodna, że nad brzegiem rosną palmy, a przy nich rząd białych chat i łodzie na cumach. Nieprawdopodobne i całkiem prawdziwe.'),
dict(id='torridon', name='Torridon', region='Highlands',
     lat=57.5460, lon=-5.5010, tags=['mountain','hiking','scenic','nature','views'], xp=50, pop=7, icon='🏔️', time='full day',
     blurb='Sandstone mountains three times older than the rock of most of the Alps, rising almost straight out of the sea loch. Liathach and Beinn Eighe are among the finest hills in Britain.',
     pl_name='Torridon',
     pl_blurb='Piaskowcowe góry trzykrotnie starsze od skał większości Alp, wznoszące się niemal prosto z morskiej zatoki. Liathach i Beinn Eighe to jedne z najpiękniejszych szczytów Wielkiej Brytanii.'),
dict(id='inverewe-garden', name='Inverewe Garden', region='Highlands',
     lat=57.7750, lon=-5.5980, tags=['nature','coast','family','scenic'], xp=30, pop=5, icon='🌸', time='2.5 hrs',
     blurb='A subtropical garden at the same latitude as Siberia, made possible by the Gulf Stream and a shelter belt planted in 1862 on what was bare rock.',
     pl_name='Ogród Inverewe',
     pl_blurb='Subtropikalny ogród na tej samej szerokości geograficznej co Syberia, możliwy dzięki Prądowi Zatokowemu i pasowi ochronnemu posadzonemu w 1862 roku na gołej skale.'),
dict(id='glen-affric', name='Glen Affric', region='Highlands',
     lat=57.2740, lon=-4.9540, tags=['forest','nature','scenic','hiking','loch'], xp=40, pop=6, icon='🌲', time='half day',
     blurb='Often called the most beautiful glen in Scotland — one of the largest surviving fragments of the ancient Caledonian pine forest, reflected in a chain of lochs.',
     pl_name='Glen Affric',
     pl_blurb='Często nazywana najpiękniejszą doliną Szkocji — jeden z największych ocalałych fragmentów pradawnego kaledońskiego lasu sosnowego, odbity w łańcuchu jezior.'),
dict(id='sandwood-bay', name='Sandwood Bay', region='North Coast 500',
     lat=58.5350, lon=-5.0500, tags=['beach','coast','hiking','nature','scenic'], xp=50, pop=5, icon='🥾', time='half day',
     blurb='A mile of pink sand with a sea stack at one end, four and a half miles from the nearest road on foot. There is no other way to reach it, which is the point.',
     pl_name='Zatoka Sandwood',
     pl_blurb='Półtora kilometra różowego piasku z ostańcem skalnym na końcu, siedem kilometrów pieszo od najbliższej drogi. Nie ma innej drogi, i o to chodzi.'),
dict(id='handa-island', name='Handa Island', region='North Coast 500',
     lat=58.3800, lon=-5.1800, tags=['island','wildlife','coast','hiking','nature'], xp=45, pop=5, icon='🐦', time='half day',
     blurb='A seabird reserve reached by a small boat from Tarbet: guillemots, razorbills and great skuas in tens of thousands on 100-metre cliffs, from April to August.',
     pl_name='Wyspa Handa',
     pl_blurb='Rezerwat ptaków morskich, do którego dopływa się łodzią z Tarbet: nurzyki, alki i wydrzyki wielkie w dziesiątkach tysięcy na 100-metrowych klifach, od kwietnia do sierpnia.'),
dict(id='ardnamurchan-point', name='Ardnamurchan Point', region='Highlands',
     lat=56.7270, lon=-6.2270, tags=['lighthouse','coast','scenic','views','drive'], xp=40, pop=5, icon='🗼', time='half day',
     blurb='The most westerly point of the British mainland, with an Egyptian-styled lighthouse and, on a clear evening, the whole chain of the Inner Hebrides laid out.',
     pl_name='Przylądek Ardnamurchan',
     pl_blurb='Najbardziej wysunięty na zachód punkt brytyjskiego lądu stałego, z latarnią w stylu egipskim, a w pogodny wieczór z widokiem na cały łańcuch Hebrydów Wewnętrznych.'),
dict(id='sligachan', name='Sligachan, Skye', region='Isle of Skye',
     lat=57.2900, lon=-6.1710, tags=['mountain','island','scenic','folklore','hiking'], xp=35, pop=7, icon='🌁', time='1.5 hrs',
     blurb='The old bridge with the Black Cuillin behind it — the most photographed view on Skye. Dip your face in the river for eternal beauty, if the legend is to be believed.',
     pl_name='Sligachan, Skye',
     pl_blurb='Stary most z Czarnymi Cuillin w tle — najczęściej fotografowany widok na Skye. Zanurz twarz w rzece, by uzyskać wieczną urodę, jeśli wierzyć legendzie.'),
dict(id='elgol', name='Elgol', region='Isle of Skye',
     lat=57.1450, lon=-6.1120, tags=['island','coast','scenic','views','village'], xp=35, pop=6, icon='⛵', time='half day',
     blurb='A slipway at the end of a long single-track road, facing the full amphitheatre of the Cuillin across Loch Scavaig. Boats run from here to Loch Coruisk.',
     pl_name='Elgol',
     pl_blurb='Slip na końcu długiej jednopasmowej drogi, naprzeciw pełnego amfiteatru Cuillin po drugiej stronie Loch Scavaig. Stąd pływają łodzie do Loch Coruisk.'),
dict(id='kilt-rock', name='Kilt Rock & Mealt Falls', region='Isle of Skye',
     lat=57.6120, lon=-6.1730, tags=['waterfall','coast','island','scenic','views'], xp=30, pop=7, icon='💧', time='45 min',
     blurb='A basalt cliff pleated like a kilt, with a waterfall dropping 60 metres straight into the sea beside it. Five minutes from the car park.',
     pl_name='Kilt Rock i wodospad Mealt',
     pl_blurb='Bazaltowy klif pofałdowany jak kilt, a obok wodospad spadający 60 metrów prosto do morza. Pięć minut od parkingu.'),
dict(id='coral-beach', name='Coral Beach, Claigan', region='Isle of Skye',
     lat=57.4900, lon=-6.6100, tags=['beach','island','coast','scenic','wildswim'], xp=30, pop=5, icon='🐚', time='2 hrs',
     blurb='Not coral but crushed maerl seaweed, bleached white, which turns the water an improbable turquoise on the rare bright day. A mile’s easy walk from the road.',
     pl_name='Koralowa plaża, Claigan',
     pl_blurb='Nie koral, lecz zmielone glony maerl, wybielone, które w rzadki pogodny dzień barwią wodę nieprawdopodobnym turkusem. Półtora kilometra łatwego marszu od drogi.'),
dict(id='iona-abbey', name='Iona Abbey', region='Argyll & the Isles',
     lat=56.3350, lon=-6.3930, tags=['island','history','ancient','mystery','coast'], xp=45, pop=6, icon='☘️', time='half day',
     blurb='Where Columba landed from Ireland in 563 and Christianity entered Scotland. The Book of Kells may have been made here. Kings of Scotland, Ireland and Norway are buried in the ground outside.',
     pl_name='Opactwo na Ionie',
     pl_blurb='Tu w 563 roku wylądował Kolumba z Irlandii i tędy chrześcijaństwo weszło do Szkocji. Być może powstała tu Księga z Kells. W ziemi obok pochowani są królowie Szkocji, Irlandii i Norwegii.'),
dict(id='kilmartin-glen', name='Kilmartin Glen', region='Argyll & the Isles',
     lat=56.1330, lon=-5.4890, tags=['ancient','history','mystery','nature'], xp=40, pop=5, icon='🪨', time='half day',
     blurb='Over 350 prehistoric monuments within six miles — cairns in a line, standing stones and rock carvings — plus Dunadd, the hill fort where the kings of Dál Riata were crowned.',
     pl_name='Dolina Kilmartin',
     pl_blurb='Ponad 350 prehistorycznych zabytków w promieniu dziesięciu kilometrów — kopce w linii, kamienne kręgi i ryty naskalne — oraz Dunadd, gród, gdzie koronowano królów Dál Riaty.'),
dict(id='inveraray-jail', name='Inveraray Jail', region='Argyll & the Isles',
     lat=56.2360, lon=-5.0740, tags=['history','family','culture','village'], xp=25, pop=5, icon='⛓️', time='1.5 hrs',
     blurb='A Georgian courthouse and prison worked by actors in costume, where you sit in the dock, get sentenced, and find out what happened next in 1820.',
     pl_name='Więzienie w Inveraray',
     pl_blurb='Georgiański sąd i więzienie obsadzone aktorami w kostiumach; siadasz na ławie oskarżonych, dostajesz wyrok i dowiadujesz się, co dalej działo się w 1820 roku.'),
dict(id='crinan-canal', name='Crinan Canal', region='Argyll & the Isles',
     lat=56.0900, lon=-5.5500, tags=['engineering','coast','cycling','scenic','village'], xp=25, pop=5, icon='⛵', time='2.5 hrs',
     blurb='Nine miles of canal built in 1801 to save boats the long haul round the Mull of Kintyre. Fifteen locks, a towpath you can cycle, and a seafood bar at the sea end.',
     pl_name='Kanał Crinan',
     pl_blurb='Czternaście kilometrów kanału zbudowanego w 1801 roku, by oszczędzić łodziom długiej drogi wokół Mull of Kintyre. Piętnaście śluz, ścieżka holownicza do jazdy rowerem i bar z owocami morza przy ujściu.'),

# ================================================= CAIRNGORMS & SPEYSIDE
dict(id='ruthven-barracks', name='Ruthven Barracks', region='Cairngorms',
     lat=57.0620, lon=-4.0350, tags=['history','ancient','scenic','views'], xp=25, pop=5, icon='🏚️', time='45 min',
     blurb='Government barracks of 1719 on a green mound, where the Jacobites gathered after Culloden and received the order to disperse. They burned it themselves and went home.',
     pl_name='Koszary Ruthven',
     pl_blurb='Rządowe koszary z 1719 roku na zielonym wzniesieniu, gdzie jakobici zebrali się po Culloden i otrzymali rozkaz rozejścia się. Sami je spalili i wrócili do domów.'),
dict(id='loch-garten', name='Loch Garten Osprey Centre', region='Cairngorms',
     lat=57.2500, lon=-3.6900, tags=['wildlife','forest','loch','family','nature'], xp=35, pop=6, icon='🦅', time='2 hrs',
     blurb='Where ospreys returned to breed in Britain in 1954 after being extinct here for decades. Live nest cameras from April to August, in old Caledonian pine forest.',
     pl_name='Centrum Rybołowów Loch Garten',
     pl_blurb='Tu w 1954 roku rybołowy wróciły do gniazdowania w Wielkiej Brytanii, po dekadach nieobecności. Kamery na gnieździe od kwietnia do sierpnia, w starym lesie kaledońskim.'),
dict(id='glenlivet', name='The Glenlivet Distillery', region='Speyside & Moray',
     lat=57.3610, lon=-3.2790, tags=['whisky','history','scenic'], xp=40, pop=7, icon='🥃', time='2 hrs',
     blurb='The first licensed distillery in the parish, in 1824, when its neighbours were all illegal and its founder carried pistols for a decade afterwards.',
     pl_name='Destylarnia The Glenlivet',
     pl_blurb='Pierwsza legalna destylarnia w parafii, w 1824 roku, gdy wszyscy sąsiedzi działali nielegalnie, a jej założyciel przez dekadę nosił przy sobie pistolety.'),
dict(id='linn-of-dee', name='Linn of Dee', region='Cairngorms',
     lat=56.9900, lon=-3.5400, tags=['river','nature','forest','scenic','hiking'], xp=25, pop=5, icon='🌊', time='1.5 hrs',
     blurb='The Dee squeezed through a narrow rock gorge you can look straight down into from a bridge, at the road end where the walks into the high Cairngorms begin.',
     pl_name='Linn of Dee',
     pl_blurb='Rzeka Dee ściśnięta w wąskim skalnym wąwozie, w który patrzysz prosto z mostu, na końcu drogi, gdzie zaczynają się szlaki w wysokie Cairngorms.'),
dict(id='corgarff-castle', name='Corgarff Castle', region='Cairngorms',
     lat=57.1650, lon=-3.2350, tags=['castle','history','scenic','skiing'], xp=25, pop=4, icon='⭐', time='1 hr',
     blurb='A white tower inside a star-shaped defensive wall, alone on the moor at the top of a road that closes in snow. Its history is grim even by Highland standards.',
     pl_name='Zamek Corgarff',
     pl_blurb='Biała wieża wewnątrz gwiaździstego muru obronnego, samotna na wrzosowisku na szczycie drogi zamykanej przy śniegu. Jej historia jest ponura nawet jak na góralskie standardy.'),

# ================================================ LOCH LOMOND & TROSSACHS
dict(id='loch-lomond-shores', name='Balloch & Loch Lomond Shores', region='Loch Lomond & Trossachs',
     lat=56.0000, lon=-4.5800, tags=['loch','family','watersports','food','village'], xp=20, pop=6, icon='🚤', time='2 hrs',
     blurb='The southern gateway to the loch: boat trips, paddleboard hire, an aquarium and a beach, forty minutes from Glasgow by train.',
     pl_name='Balloch i Loch Lomond Shores',
     pl_blurb='Południowa brama jeziora: rejsy, wypożyczalnia desek SUP, akwarium i plaża, czterdzieści minut pociągiem z Glasgow.'),
dict(id='the-cobbler', name='The Cobbler (Ben Arthur)', region='Loch Lomond & Trossachs',
     lat=56.2000, lon=-4.7600, tags=['hiking','mountain','climbing','views','scenic'], xp=45, pop=7, icon='🪨', time='5 hrs',
     blurb='The most distinctive skyline in the southern Highlands. To have truly climbed it you must thread the eye of the summit rock and step round onto the exposed top block.',
     pl_name='The Cobbler (Ben Arthur)',
     pl_blurb='Najbardziej charakterystyczna sylwetka w południowych Highlands. Aby naprawdę go zdobyć, trzeba przejść przez ucho szczytowej skały i obejść ekspozycję na wierzchołkowy blok.'),
dict(id='bracklinn-falls', name='Callander & Bracklinn Falls', region='Loch Lomond & Trossachs',
     lat=56.2500, lon=-4.2000, tags=['waterfall','forest','hiking','family','village'], xp=25, pop=5, icon='🌉', time='2 hrs',
     blurb='A gorge and a footbridge above tumbling falls, twenty minutes’ walk from a town full of tearooms. The original bridge was carried away by a flood in 2004.',
     pl_name='Callander i wodospady Bracklinn',
     pl_blurb='Wąwóz i kładka nad rwącymi wodospadami, dwadzieścia minut spacerem od miasteczka pełnego herbaciarni. Pierwotny most porwała powódź w 2004 roku.'),
dict(id='inchmahome', name='Inchmahome Priory', region='Loch Lomond & Trossachs',
     lat=56.1750, lon=-4.3000, tags=['island','history','ancient','loch','mystery'], xp=30, pop=5, icon='🛶', time='2 hrs',
     blurb='An island priory on the Lake of Menteith, reached by ferry, where the four-year-old Mary, Queen of Scots was hidden in 1547 before being shipped to France.',
     pl_name='Przeorat Inchmahome',
     pl_blurb='Wyspiarski przeorat na Lake of Menteith, dostępny promem, gdzie w 1547 roku ukryto czteroletnią Marię Stuart, zanim wysłano ją do Francji.'),
]
